/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package ejemploframe;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class EjemploFrameApp extends java.awt.Frame {

    /**
     * Creates new form EjemploFrameApp
     */
    public EjemploFrameApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        EjemploFrameApp f = new EjemploFrameApp();
        f.setSize(600, 400);
        f.setBackground(Color.pink);
        f.setTitle("Ejemplo Práctica 3");
        f.setLocation(300, 100);
        
        MiCanvas cv = new MiCanvas(600, 400);
        f.add(cv);
        f.setVisible(true);
        
        Recurso r = new Recurso(cv);
        for (int i = 0; i < 10; i++) {
            r.incrementa(1);
        }
        
        Sumador h1 = new Sumador(r, 0); 
        Sumador h2 = new Sumador(r, 1); 
        Sumador h3 = new Sumador(r, 1); 
        
        h1.start();
        h2.start();
        h3.start();
        
        h1.join();
        h2.join();
        h3.join();
        
        int resul[] = r.getContadores();
        System.out.println("El contador 1 vale " + resul[0]);
        System.out.println("El contador 2 vale " + resul[1]);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
