
import java.util.Random;
import java.util.concurrent.Semaphore;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *
 * @author Manu
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Generador g = new Generador();
        int alto = 900, ancho = 600;
        CanvasRobots canvas = new CanvasRobots(alto, ancho);
        g.setSize(alto, ancho);
        g.add(canvas);
        g.setVisible(true);
        
        Semaphore litroR = new Semaphore(3); 
        Semaphore litroB = new Semaphore(3);
        Semaphore huecoR = new Semaphore(10);
        Semaphore huecoB = new Semaphore(10);

        RobotTR reponedor = new RobotTR(litroR, huecoR, litroB, huecoB, canvas);
        Thread TA1 = new RobotTA(1, litroR, huecoR, litroB, huecoB, canvas);
        Thread TA2 = new RobotTA(2, litroR, huecoR, litroB, huecoB, canvas);
        Thread TB1 = new Thread( new RobotTB(1, litroR, huecoR, litroB, huecoB, canvas));
        Thread TB2 = new Thread(new RobotTB(2, litroR, huecoR, litroB, huecoB, canvas));
        Random rnd = new Random();
        rnd.setSeed(System.currentTimeMillis());
 
        try {
            reponedor.start();
            TA1.start();
            TA2.start();
            TB1.start();
            TB2.start();
            
            reponedor.join();
            TA1.join();
            TA2.join();
            TB1.join();
            TB2.join();
            System.out.println("\nFin de todos los hilos tipo A y B");
            reponedor.interrupt();
            //reponedor.join(); 
            System.out.println("\nFin del hilo reponedor");

            System.exit(0);
        } catch (InterruptedException ex) {
            System.out.println("Error de tipo :" + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
