/* UriumHeaderParser.java */
/* Generated By:JavaCC: Do not edit this line. UriumHeaderParser.java */
//------------------------------------------------------------------//
//                        COPYRIGHT NOTICE                          //
//------------------------------------------------------------------//
// Copyright (c) 2024, Francisco J. Moreno Velo                     //
//                                                                  //
// Permission is hereby granted, free of charge, to any person      //
// obtaining a copy of this software and associated documentation   //
// files (the "Software"), to deal in the Software without          //
// restriction, including without limitation the rights to use,     //
// copy, modify, merge, publish, distribute, sublicense, and/or     //
// sell copies of the Software, and to permit persons to whom the   //
// Software is furnished to do so, subject to the following         //
// conditions:                                                      //
//                                                                  //
// - The above copyright notice and this permission notice shall be //
//   included in all copies or substantial portions of the Software.//
//                                                                  //
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,  //
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES  //
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND         //
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT      //
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,     //
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     //
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR    //
// OTHER DEALINGS IN THE SOFTWARE.                                  //
//------------------------------------------------------------------//

//------------------------------------------------------------------//
//                      Universidad de Huelva                       //
//          Departamento de Tecnologías de la Información           //
//   Área de Ciencias de la Computación e Inteligencia Artificial   //
//------------------------------------------------------------------//
//                                                                  //
//                         Urium compiler                           //
//                                                                  //
//------------------------------------------------------------------//

package urium.parser;

import urium.ast.*;
import urium.ast.struct.*;
import java.util.Vector;

public class UriumHeaderParser implements UriumHeaderParserConstants {

        //----------------------------------------------------------------//
        //                         Private members                        //
        //----------------------------------------------------------------//

        /**
	 * Error count
	 */
        private int errorCount;

        /**
	 * Error message
	 */
        private String errorMsg;

        //----------------------------------------------------------------//
        //                           Public methods                       //
        //----------------------------------------------------------------//

        /**
	 * Method to parse an Urium file
	 */
        public LibraryDeclaration parse(String libname)
        {
                this.errorCount = 0;
                this.errorMsg = "";
                try
                {
                        LibraryDeclaration library = tryCompilationUnit(libname);
                        return library;
                }
                catch(Throwable e)
                {
                        catchError(e);
                        return null;
                }
        }

        /**
	 * Gets the number of errors in the analysis
	 */
        public int getErrorCount()
        {
                return this.errorCount;
        }

        /**
	 * Get the error message of the analysis
	 */
        public String getErrorMsg()
        {
                return this.errorMsg;
        }

        //----------------------------------------------------------------//
        //                 Private methods (semantic checks)              //
        //----------------------------------------------------------------//

        /**
	 * Stores a parse error
	 */
        private void catchError(Throwable ex)
        {
                this.errorCount++;
                this.errorMsg += ex.toString();
        }

        /**
	 * Checks that the library name corresponds to the source file name 
	 */
        private boolean verifyLibraryName(Token tk, String name, LibraryDeclaration library)
        {
                if(!name.equals(library.getName()))
                {
                        int errorcode = SemanticException.LIBRARY_NAME_EXCEPTION;
                        catchError(new SemanticException(errorcode,tk));
                        return false;
                }
                return true;
        }

        /**
	 * Checks that a certain procedure has not been previously defined in the library
	 */
        private boolean verifyNonDuplicatedProcedure(Token tk, Procedure proc, LibraryDeclaration library)
        {
                DataType[] type = proc.getArgumentTypes();
                Procedure dup = library.getAnyProcedure(tk.image,type);
                if(dup != null)
                {
                        int errorcode = SemanticException.DUPLICATE_PROCEDURE_EXCEPTION;
                        catchError(new SemanticException(errorcode,tk));
                        return false;
                }
                return true;
        }

        /**
	 * Checks that an argument name is not duplicated
	 */
        private boolean verifyNonDuplicatedArgument(Token tk, Vector<Variable> arguments)
        {
                if(arguments.contains(tk.image))
                {
                        int errorcode = SemanticException.DUPLICATE_ARGUMENT_EXCEPTION;
                        catchError(new SemanticException(errorcode,tk));
                        return false;
                }
                return true;
        }

        //----------------------------------------------------------------//
        //                 Private methods (semantic actions)             //
        //----------------------------------------------------------------//

    /**
     * Semantic action that creates a procedure in a library
     */
        private void actionLibraryProcedure(int acc, Token tid, Vector<Variable> arguments, LibraryDeclaration library)
        {
            Procedure proc = new Procedure(acc, tid.image, library.getName());
            proc.addArgumentList(arguments);
                if(!verifyNonDuplicatedProcedure(tid,proc,library)) return;
                library.addProcedure(proc);
        }

        /**
     * Semantic action that adds an argument to an argument list
     */
        private void actionAddArgument(DataType type, Token tk, Vector<Variable> arguments)
        {
          if(!verifyNonDuplicatedArgument(tk,arguments)) return;
          arguments.add(new Variable(type, tk.image) );
        }

/**************************************************************/
/*             SYNTACTIC DESCRIPTION STARTS HERE              */
/**************************************************************/

/**
 * Parses the full content of a source file
 *
 * CompilationUnit ::= (InportClause)* UriumDecl
 */
  final public LibraryDeclaration tryCompilationUnit(String name) throws ParseException {int[] lsync = { };
  int[] rsync = { EOF };
  LibraryDeclaration library = new LibraryDeclaration(name);
    try {
      parseCompilationUnit(library);
      jj_consume_token(0);
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
    return library;
}

/**
 * Parses the full content of a source file
 *
 * CompilationUnit ::= (InportClause)* UriumDecl
 */
  final public void parseCompilationUnit(LibraryDeclaration library) throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IMPORT:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      tryImportClause(library);
    }
    tryUriumDecl(library);
}

/**
 * Parses an import clause
 *
 * ImportClause ::= <IMPORT> <IDENTIFIER> (<DOT> <IDENTIFIER>)* (<AS> <IDENTIFIER>)? <SEMICOLON> 
 */
  final public void tryImportClause(LibraryDeclaration library) throws ParseException {int[] lsync = { SEMICOLON };
  int[] rsync = { IMPORT, LIBRARY, NATIVE };
    try {
      parseImportClause(library);
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
}

/**
 * Parses an import clause
 *
 * ImportClause ::= <IMPORT> <IDENTIFIER> (<DOT> <IDENTIFIER>)* (<AS> <IDENTIFIER>)? <SEMICOLON> 
 */
  final public void parseImportClause(LibraryDeclaration library) throws ParseException {Token tid;
  String name;
  String alias = null;
    jj_consume_token(IMPORT);
    tid = jj_consume_token(IDENTIFIER);
name = tid.image;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(DOT);
      tid = jj_consume_token(IDENTIFIER);
name += "."+tid.image;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case AS:{
      jj_consume_token(AS);
      tid = jj_consume_token(IDENTIFIER);
alias = tid.image;
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
if(alias == null) alias = name;
    library.addImportedLibrary(alias,name);
}

/**
 * Parses the declaration of a library (ordinary or native)
 *
 * UriumDecl ::=  LibraryDecl |  NativeDecl 
 */
  final public void tryUriumDecl(LibraryDeclaration library) throws ParseException {int[] lsync = { };
  int[] rsync = { };
    try {
      parseUriumDecl(library);
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
}

/**
 * Parses the declaration of a library (ordinary or native)
 *
 * UriumDecl ::=  LibraryDecl |  NativeDecl 
 */
  final public void parseUriumDecl(LibraryDeclaration library) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LIBRARY:{
      tryLibraryDecl(library);
      break;
      }
    case NATIVE:{
      tryNativeDecl(library);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/**
 * Parses the declaration of an ordinary library
 *
 * LibraryDecl ::=  <LIBRARY> <IDENTIFIER> (<DOT> <IDENTIFIER>)* <LBRACE> ( ProcedureDecl )* <RBRACE> 
 */
  final public void tryLibraryDecl(LibraryDeclaration library) throws ParseException {int[] lsync = { };
  int[] rsync = { };
    try {
      parseLibraryDecl(library);
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
}

/**
 * Parses the declaration of an ordinary library
 *
 * LibraryDecl ::=  <LIBRARY> <IDENTIFIER> (<DOT> <IDENTIFIER>)* <LBRACE> ( ProcedureDecl )* <RBRACE> 
 */
  final public void parseLibraryDecl(LibraryDeclaration library) throws ParseException {Token tid, tid2;
  String name;
    jj_consume_token(LIBRARY);
    tid = jj_consume_token(IDENTIFIER);
name = tid.image;
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      jj_consume_token(DOT);
      tid2 = jj_consume_token(IDENTIFIER);
name += "."+tid2.image;
    }
verifyLibraryName(tid,name,library);
    jj_consume_token(LBRACE);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PRIVATE:
      case PUBLIC:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      tryProcedureDecl(library);
    }
    jj_consume_token(RBRACE);
}

/**
 * Parses the declaration of a procedure
 *
 * ProcedureDecl ::= Access <PROC> <IDENTIFIER> ArgumentDecl ProcedureBody
 */
  final public void tryProcedureDecl(LibraryDeclaration library) throws ParseException {int[] lsync = { };
  int[] rsync = { PUBLIC, PRIVATE };
    try {
      parseProcedureDecl(library);
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
}

/**
 * Parses the declaration of a procedure
 *
 * ProcedureDecl ::= Access <PROC> <IDENTIFIER> ArgumentDecl ProcedureBody
 */
  final public void parseProcedureDecl(LibraryDeclaration library) throws ParseException {int acc;
  Token tid;
  Vector<Variable> args;
    acc = tryAccess();
    jj_consume_token(PROC);
    tid = jj_consume_token(IDENTIFIER);
    args = tryArgumentDecl();
    ProcedureBody();
actionLibraryProcedure(acc,tid,args,library);
}

/**
 * Parses the declaration of a native library
 *
 * NativeDecl ::=  <NATIVE> <IDENTIFIER> (<DOT> <IDENTIFIER>)* <LBRACE> ( NativeProcedure )* <RBRACE> 
 */
  final public void tryNativeDecl(LibraryDeclaration library) throws ParseException {int[] lsync = { };
  int[] rsync = { };
  library.setNative(true);
    try {
      parseNativeDecl(library);
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
}

/**
 * Parses the declaration of a native library
 *
 * NativeDecl ::=  <NATIVE> <IDENTIFIER> (<DOT> <IDENTIFIER>)* <LBRACE> ( NativeProcedure )* <RBRACE> 
 */
  final public void parseNativeDecl(LibraryDeclaration library) throws ParseException {Token tid, tid2;
  String name;
    jj_consume_token(NATIVE);
    tid = jj_consume_token(IDENTIFIER);
name = tid.image;
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      jj_consume_token(DOT);
      tid2 = jj_consume_token(IDENTIFIER);
name += "."+tid2.image;
    }
verifyLibraryName(tid,name,library);
    jj_consume_token(LBRACE);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PRIVATE:
      case PUBLIC:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_6;
      }
      tryNativeProcedure(library);
    }
    jj_consume_token(RBRACE);
}

/**
 * Parses the declaration of a procedure of a native library
 *
 * NativeProcedure ::= Access <PROC> <IDENTIFIER> ArgumentDecl <SEMICOLON>
 */
  final public void tryNativeProcedure(LibraryDeclaration library) throws ParseException {int[] lsync = { };
  int[] rsync = { PUBLIC, PRIVATE };
    try {
      parseNativeProcedure(library);
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
}

/**
 * Parses the declaration of a procedure of a native library
 *
 * NativeProcedure ::= Access <PROC> <IDENTIFIER> ArgumentDecl <SEMICOLON>
 */
  final public void parseNativeProcedure(LibraryDeclaration library) throws ParseException {int acc;
  Token tid;
  Vector<Variable> args;
    acc = tryAccess();
    jj_consume_token(PROC);
    tid = jj_consume_token(IDENTIFIER);
    args = tryArgumentDecl();
    jj_consume_token(SEMICOLON);
actionLibraryProcedure(acc,tid,args,library);
}

/**
 * Parses an access modifier
 *
 * Access ::= <PUBLIC> | <PRIVATE>
 */
  final public int tryAccess() throws ParseException {int[] lsync = { };
  int[] rsync = { PROC };
  int acc = Access.PUBLIC_ACCESS;
    try {
      acc = parseAccess();
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
    return acc;
}

/**
 * Parses an access modifier
 *
 * Access ::= <PUBLIC> | <PRIVATE>
 */
  final public int parseAccess() throws ParseException {int acc;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PUBLIC:{
      jj_consume_token(PUBLIC);
acc = Access.PUBLIC_ACCESS;
      break;
      }
    case PRIVATE:{
      jj_consume_token(PRIVATE);
acc = Access.PRIVATE_ACCESS;
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    return acc;
}

/**
 * Parses the declaration of arguments of a procedure
 *
 * ArgumentDecl ::= <LPAREN> ( Argument ( <COMMA> Argument )* )? <RPAREN>
 */
  final public Vector<Variable> tryArgumentDecl() throws ParseException {int[] lsync = { RPAREN };
  int[] rsync = { LBRACE };
  Vector<Variable> args = null;
    try {
      args = parseArgumentDecl();
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
    return args;
}

/**
 * Parses the declaration of arguments of a procedure
 *
 * ArgumentDecl ::= <LPAREN> ( Argument ( <COMMA> Argument )* )? <RPAREN>
 */
  final public Vector<Variable> parseArgumentDecl() throws ParseException {Vector<Variable> args = new Vector<Variable>();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BOOLEAN:
    case CHAR:
    case INT:
    case OUT:{
      tryArgument(args);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_7;
        }
        jj_consume_token(COMMA);
        tryArgument(args);
      }
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    return args;
}

/**
 * Parses the declaration of an argument
 *
 * Argument ::= ArgumentType <IDENTIFIER>
 */
  final public void tryArgument(Vector<Variable> args) throws ParseException {int[] lsync = { };
  int[] rsync = { COMMA, RPAREN };
    try {
      parseArgument(args);
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
}

/**
 * Parses the declaration of an argument
 *
 * Argument ::= ArgumentType <IDENTIFIER>
 */
  final public void parseArgument(Vector<Variable> args) throws ParseException {DataType type;
  Token tid;
    type = tryArgumentType();
    tid = jj_consume_token(IDENTIFIER);
actionAddArgument(type,tid,args);
}

/**
 * Parses the data type of an argument
 *
 * ArgumentType ::= ( <OUT> )? ( <INT> | <CHAR> | <BOOLEAN> )
 */
  final public DataType tryArgumentType() throws ParseException {int[] lsync = { };
  int[] rsync = { IDENTIFIER };
  DataType type = DataType.mismatch_type;
    try {
      type = parseArgumentType();
    } catch (Exception ex) {
catchError(ex);
    skipTo(lsync,rsync);
    }
    return type;
}

/**
 * Parses the data type of an argument
 *
 * ArgumentType ::= ( <OUT> )? ( <INT> | <CHAR> | <BOOLEAN> )
 */
  final public DataType parseArgumentType() throws ParseException {DataType type;
  boolean out = false;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OUT:{
      jj_consume_token(OUT);
out = true;
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
type = (out? DataType.int_ref_type: DataType.int_type);
      break;
      }
    case CHAR:{
      jj_consume_token(CHAR);
type = (out? DataType.char_ref_type: DataType.char_type);
      break;
      }
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
type = (out? DataType.boolean_ref_type: DataType.boolean_type);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    return type;
}

  void ProcedureBody() throws ParseException {Token tk = getNextToken();  // Consume el caracter "{"
  int level = 1;
  while(level != 0)
  {
    tk = getNextToken();
        if(tk.kind == EOF) break;
    else if(tk.kind == LBRACE) level ++;
    else if(tk.kind == RBRACE) level --;
  }
  }

  void skipTo(int[] left, int[] right) throws ParseException {Token prev = getToken(0);
  Token next = getToken(1);
  boolean flag = false;
  if(prev.kind == EOF || next.kind == EOF) flag = true;
  for(int i=0; i<left.length; i++) if(prev.kind == left[i]) flag = true;
  for(int i=0; i<right.length; i++) if(next.kind == right[i]) flag = true;

  while(!flag)
  {
    getNextToken();
    prev = getToken(0);
    next = getToken(1);
    if(prev.kind == EOF || next.kind == EOF) flag = true;
    for(int i=0; i<left.length; i++) if(prev.kind == left[i]) flag = true;
    for(int i=0; i<right.length; i++) if(next.kind == right[i]) flag = true;
  }
  }

  /** Generated Token Manager. */
  public UriumHeaderParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[13];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x8000,0x0,0x100,0x60000,0x0,0x500000,0x0,0x500000,0x500000,0x0,0x90600,0x80000,0x10600,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x40,0x0,0x0,0x40,0x0,0x40,0x0,0x0,0x20,0x0,0x0,0x0,};
	}

  /** Constructor with InputStream. */
  public UriumHeaderParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public UriumHeaderParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new UriumHeaderParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public UriumHeaderParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new UriumHeaderParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new UriumHeaderParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public UriumHeaderParser(UriumHeaderParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(UriumHeaderParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[54];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 13; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 54; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
