/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package p9_pcd;

import java.util.Random;

/**
 *
 * @author Manu
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Generador gen = new Generador();
        int ancho = 900, alto = 600;
        Canvas_Gasolinera cv = new Canvas_Gasolinera(ancho, alto);
        gen.setSize(ancho, alto);
        gen.add(cv);
        gen.setVisible(true);
        
        Gasolinera gas = new Gasolinera(cv);
        Thread[] vehiculos = new Thread[30];
        Random rnd = new Random();
        rnd.setSeed(System.currentTimeMillis());
        
        try {
            for(int i = 0; i < vehiculos.length; i++) {
                int rand = rnd.nextInt(10);
                if(rand == 0) 
                    vehiculos[i] = new Ambulancia(i+1, gas);
                else if(rand > 0 && rand < 5)
                    vehiculos[i] = new Thread(new Camion(i+1, gas));
                else
                    vehiculos[i] = new Coche(i+1, gas);
                
                vehiculos[i].start();
                Thread.sleep((rnd.nextInt(1) + 1) * 1000);
            }
            for (int i = 0; i < vehiculos.length; i++) {
                vehiculos[i].join();
            }
            
            Thread.sleep(3000);
            System.out.println("\nFin de todos los hilos");
            System.exit(0);
        } catch (InterruptedException e) {
            System.out.println("Error de tipo :" + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
