/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package p8;

import java.util.Random;

/**
 *
 * @author Manu
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Generador g = new Generador();
        CanvasCentro canvas = new CanvasCentro(900, 600);
        g.setSize(900, 600);
        g.add(canvas);
        g.setVisible(true);
        
        Centro c = new Centro();
        Thread[] pacientes = new Thread[50];
        Thread limpiador = new Limpiador(canvas, c);
        limpiador.start();
        Random rnd = new Random();
        rnd.setSeed(System.currentTimeMillis());
 
        try {
            for (int i = 0; i < pacientes.length; i++) {
                if (rnd.nextInt(4) != 0) {
                    pacientes[i] = new PNormal(i+1, canvas, c);
                } else {
                    pacientes[i] = new Thread(new PInfeccioso(i+1, canvas, c));
                }
                pacientes[i].start();
                Thread.sleep((rnd.nextInt(2) + 2) * 1000);
            }

            for (int i = 0; i < pacientes.length; i++) {
                pacientes[i].join();
            }
            
            System.out.println("Fin de todos los pacientes");
            limpiador.interrupt();
            limpiador.join();
            System.out.println("Fin del hilo limpiador");
            System.exit(0);
        } catch (InterruptedException ex) {
            System.out.println("Error de tipo :" + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
