/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package p7;

import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

/**
 *
 * @author Manu
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        Generador g = new Generador();
        CanvasPool cv = new CanvasPool(900, 600);
        g.setSize(900, 600);
        g.add(cv);
        g.setVisible(true);
        ExecutorService poolCivil = Executors.newFixedThreadPool(7);
        ExecutorService poolMilitar = Executors.newFixedThreadPool(7);

        ArrayList<Future<Integer>> fc = new ArrayList<>();
        ArrayList<Future<Integer>> fm = new ArrayList<>();
    
        Control control = new Control();
        Random rnd = new Random();
        rnd.setSeed(System.currentTimeMillis());
        for (int i = 0; i < 50; i++) {
            if (rnd.nextInt(2) == 0) {
                Militar m = new Militar(control, cv, i+1);
                fm.add(poolMilitar.submit(m));
            } else {
                Civil c = new Civil(control, cv, i+1);
                fc.add(poolCivil.submit(c));
            }
            Thread.sleep(500);
        }
        System.out.println("\nTodas las tareas lanzadas..\n");
        
        poolMilitar.shutdown();
        poolCivil.shutdown();
        System.out.println("\nSe han eliminado los ThreadPool\n");
        
        int tiempoM = 0; int tiempoC = 0;
        for (int i = 0; i < fm.size(); i++) {
            try {
                tiempoC += fm.get(i).get(); // Equivalente a un join
            } catch (InterruptedException | ExecutionException ex) {
                System.out.println(ex.getMessage());
            }
        }
        for (int i = 0; i < fc.size(); i++) {
            try {
                tiempoM += fc.get(i).get();
            } catch (InterruptedException | ExecutionException ex) {
                System.out.println(ex.getMessage());
            }
        }
        System.out.println("Cantidad de Militares : " + fm.size() + " .. Cantidad de Civiles : " + fc.size());
        System.out.println("Tiempo de Militares en el arco : " + tiempoM);
        System.out.println("Tiempo de Civiles en el arco : " + tiempoC);
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
